# Generated by Django 3.2.10 on 2022-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarPickUp', '0004_auto_20220519_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='video_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='video_record',
            field=models.FileField(null=True, upload_to='records'),
        ),
    ]
